<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#F2F2F2" style="table-layout:fixed"><tbody><tr><td>
<table width="590" border="0" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tbody><tr>
<td height="40" valign="bottom"><img src="https://ci5.googleusercontent.com/proxy/JmQhPyURrrhWXT_tiXyAvp7iKPykOGfg64EJLZEjsA9e1tC_ideINJyAn7fLbpSdJm9qfM7nmcC2HzqmaRKWw3-Oa9HHOO0HNoMpd2Je1CDr3aFV2G8=s0-d-e1-ft#http://pages.bullhorn.com/rs/bullhorninc/images/curv-top-sdw.png" style="display:block" width="589" height="18" border="0" class="CToWUd"></td>
</tr>
</tbody></table>

<table width="100%" bgcolor="#FFFFFF" border="0" cellspacing="0" cellpadding="0" style="background-color:#ffffff;border-bottom:0px solid #920606"><tbody><tr><td width="15" colspan="3" style="font-size:1px;border-collapse:collapse;margin:0;padding:0"><div style="background-color:#b80909"><img src="http://www.bullhorn.org.uk/images/Bullhorn-header-generic.png" alt="" width="593" height="94" class="CToWUd"></div>
</td>
</tr>
</tbody></table>

<table width="100%" bgcolor="#FFFFFF" border="0" cellspacing="0" cellpadding="0" style="background-color:#ffffff;font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#5e5d5d"><tbody><tr>
<td height="10" style="font-size:1px;border-collapse:collapse;margin:0;padding:0" colspan="3">&nbsp;</td>
</tr>
<tr><td width="15" style="font-size:1px">&nbsp;</td>
<td valign="top" style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#5e5d5d;line-height:18px"><div><p style="font-family:Arial,Helvetica,sans-serif;font-size:12px;font-weight:normal"><span style="font-size:20px"><strong style="font-size:20px;font-family:arial,helvetica,sans-serif">We received your request for a Password change!</strong></span></p>
<div><span style="font-family:arial,helvetica,sans-serif"><span style="font-size:16px"><strong>&nbsp;</strong></span></span><br><span style="font-family:arial,helvetica,sans-serif;font-size:16px"> Hello!</span></div>
<div><span style="font-family:arial,helvetica,sans-serif;font-size:16px"><br></span></div>
<div><span style="font-family:arial,helvetica,sans-serif;font-size:16px">Someone requested that the password be reset for this account. If this was a mistake, please sign in to verify your security questions. Please visit the following address:<br> 
<a href="http://www.bullhorn.org.uk/?action=rp&key=bgad48EmW9Kt0lin6xHD">http://www.bullhorn.org.uk/?action=rp&key=bgad48EmW9Kt0lin6xHD</a>
</span></div>
<div><span style="font-family:arial,helvetica,sans-serif;font-size:16px"><br></span></div>
<div><span style="font-family:arial,helvetica,sans-serif;font-size:16px">Regards,</span></div>
<div><span style="font-family:arial,helvetica,sans-serif;font-size:16px"><br></span></div>
<div><span style="font-family:arial,helvetica,sans-serif;font-size:16px">The Bullhorn Team</span></div></div>
</td>
<td width="15" style="font-size:1px;border-collapse:collapse;margin:0;padding:0">&nbsp;</td>
</tr>
<tr>
<td height="20" style="font-size:1px;border-collapse:collapse;margin:0;padding:0" colspan="3">&nbsp;</td>
</tr>
</tbody></table>


<table width="100%" border="0" cellspacing="0" cellpadding="0" style="font-family:Arial,Helvetica,sans-serif;font-size:11px;color:#000000;text-align:center"><tbody><tr>
<td height="40" valign="top"><img src="https://ci6.googleusercontent.com/proxy/WLJQ5-L090cvNpUvWQZuqW5or4Wyg0A5m-6m4U0Q2kl2DnbQ5D0FMExQB9QmKqEA6ytic6Fe1DBPlP1oQKHeHHIa0f0w_zfAi3STAYB7_LxsT2szS1DWn8g=s0-d-e1-ft#http://pages.bullhorn.com/rs/bullhorninc/images/curv-bottom-sdw.png" width="589" height="34" style="display:block" border="0" class="CToWUd"></td>
</tr>
<tr><td style="color:#5e5d5d"><div><span style="font-weight:bold">Bullhorn, Inc.</span>, 33-41 Farnsworth Street, 5th Floor, Boston, MA 02210<br>
<a style="color:#5e5d5d;text-decoration:none" href="http://go.bullhorn.com/B400sY0Ke000w0zQ0444TUy" target="_blank">Contact Us</a></div>
</td>
</tr>
<tr>
<td height="30" style="font-size:1px;border-collapse:collapse;margin:0;padding:0">&nbsp;</td>
</tr>
</tbody></table>
</td>
</tr>
</tbody></table>
</td>
</tr>
</tbody></table>
