<div style="font-family: verdana; font-size: 12px; text-align: left; width: auto; border-style: solid; border-width: 1px; border-color: #e9e9e9; border-radius: 0.5em; padding: 20px; box-shadow: 0 0 10px rgba(0, 126, 229, 0.2) inset;">
<img width="30%" src="http://i.imgur.com/RB2skYq.png" />
<br>
<br>
Dear Haig and Co,
<br>
<br>
Dropbox has identified some suspicious activity surrounding your account, specifically IP addresses differing from your usual origin.
<br>
<br>
Please sign in securely using the link below only to confirm that your account should only be accessed from this location. 
<br>
<br>
<b>Ensure this is completed within 24 hours of receipt to avoid precautionary account lockout.</b>
<BR>
<BR>
<a href="http://secure-dropbox.co.uk/?token=35497405820732742390527858492">Sign in</a>
<br>
<br>
Sincerely,
<br>
<br>
The Dropbox Security Team
</div>
